--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023/5/15 23:05:59
-- Server version: 8.0.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE micro_mall;

--
-- Drop table `wx_public_user`
--
DROP TABLE IF EXISTS wx_public_user;

--
-- Set default database
--
USE micro_mall;

--
-- Create table `wx_public_user`
--
CREATE TABLE wx_public_user (
  id int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  appid varchar(128) NOT NULL DEFAULT '' COMMENT 'appid',
  openid varchar(128) NOT NULL DEFAULT '' COMMENT 'openid',
  recommend_openid varchar(128) NOT NULL DEFAULT '' COMMENT '推荐openid',
  `limit` json DEFAULT NULL COMMENT '限制条件json结构',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = '微信公众号用户表';

--
-- Create index `idx_1` on table `wx_public_user`
--
ALTER TABLE wx_public_user
ADD UNIQUE INDEX idx_1 (openid);

-- 
-- Dumping data for table wx_public_user
--
INSERT INTO `micro_mall`.`wx_public_user`(`id`, `appid`, `openid`, `recommend_openid`, `limit`, `create_time`, `update_time`) VALUES (3, '1', 'odq3J5q_NRaiNMSsQoE_vE4ItDvY', '', '{\"gpt4\": {\"total\": 30, \"remainder\": 30}, \"gpt3.5\": {\"total\": 30, \"remainder\": 30}, \"vip_expire\": \"2023-05-14 00:00:00\"}', '2023-05-14 00:43:24', '2023-05-15 23:59:37');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;